# Generated by Django 3.0.4 on 2020-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default='rand-ed57941d-0e4a-4ccd-8b41-ca08b2a7d950', max_length=50)),
                ('post_type_id', models.CharField(default='rand', max_length=10)),
                ('parent_id', models.CharField(max_length=10, null=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('comment_count', models.IntegerField(db_index=True, null=True)),
                ('view_count', models.IntegerField(db_index=True, null=True)),
                ('answer_count', models.IntegerField(db_index=True, null=True)),
                ('score', models.IntegerField(db_index=True, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('body', models.CharField(max_length=1000, null=True)),
                ('owner_user_id', models.CharField(max_length=10, null=True)),
                ('last_editor_user_id', models.CharField(max_length=10, null=True)),
                ('last_edit_date', models.DateTimeField(null=True)),
                ('last_activity_date', models.DateTimeField(null=True)),
                ('comment_code', models.CharField(default='rand-d81355cf-6197-46a5-8bdc-35eae442221f', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
